version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ml_models:/app/models
    environment:
      - ENVIRONMENT=development
      - PYTHONUNBUFFERED=1
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/development/google_cloud.json
      - DB_HOST=cloudsql-proxy
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    depends_on:
      - cloudsql-proxy
      - qdrant

  cloudsql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:latest
    command:
      - "/cloud_sql_proxy"
      - "-instances=${GOOGLE_CLOUD_PROJECT}:us-central1:ecommerce-db=tcp:0.0.0.0:5432"
      - "-credential_file=/secrets/cloudsql/credentials.json"
    volumes:
      - ./credentials/development/google_cloud.json:/secrets/cloudsql/credentials.json
    ports:
      - "5432:5432"

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT_ALLOW_CORS=true

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://backend:8080
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
    env_file:
      - ./frontend/.env

volumes:
  qdrant_data:
  ml_models: 